version: '3'

services:
  deemon:
    image: ghcr.io/brugr/deemon:latest
    container_name: deemon
    environment:
      - SLEEP_TIME=24h
    volumes:
      - /path/to/config:/config
      - /path/to/config/deemix:/deemix
      - /path/to/downloads:/downloads